[profile.default]
src = "src"
out = "out"
libs = [
    'node_modules',
    'lib'
]
solc = "0.8.20"
optimizer = true
optimizer_runs = 200
verbosity = 3

remappings = [
    '@openzeppelin/=node_modules/@openzeppelin/',
    '@openzeppelin-upgradeable/=node_modules/@openzeppelin/contracts-upgradeable/',
    '@openzeppelin/contracts-upgradeable/=node_modules/@openzeppelin/contracts-upgradeable/',
    'forge-std/=lib/forge-std/src/'
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[profile.ci]
verbosity = 4
fuzz_runs = 1000
[profile.ci.fuzz]
runs = 1000

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"
localhost = "http://localhost:8545"
